PRD-1041: Implemented library
RonasIT/axios-api-client pull request #1
Opened 2024-03-12 22:11 UTC by RuslanAktaev

Refs: https://app.clickup.com/t/24336023/PRD-1041

2024-03-12 22:15 UTC, RuslanAktaev commented
@ipakhomov example of usage is provided in the [README.md](https://github.com/RonasIT/axios-api-client/blob/6b8c719a087dddb26daf0f683f519d1b0ecaf731/README.md).

2024-03-14 16:06 UTC, ipakhomov requested changes
@RuslanAktaev please find my suggestions above

2024-03-14 16:06 UTC, ipakhomov commented on README.md
> +3. Remove `@reduxjs/toolkit` and `@ronas-it/rtkq-entity-api` from devDependencies
Not sure we even need this dependencies because package should be able to be used without them

2024-03-14 16:06 UTC, ipakhomov commented on src/utils/base-query.ts
> +export const axiosBaseQuery: BaseQueryFunction = createAxiosBaseQuery({
I don't think we should include this into the library

2024-03-14 16:06 UTC, ipakhomov commented on src/utils/api-creator.ts
> +export const createAppApi = createApiCreator({
This is also should be project specific. No need to have this in library

2024-03-15 13:22 UTC, ipakhomov requested changes
@RuslanAktaev few more comments to address

2024-03-15 13:22 UTC, ipakhomov commented on README.md
> +@ronas-it/axios-api-client
```suggestion
npm i @ronas-it/axios-api-client
```

2024-03-15 13:22 UTC, ipakhomov commented on README.md
> +export { ErrorBoundary } from 'expo-router';
Let's avoid any mentions of react-native. Library is indented to be used with any project that uses axios and typescript. Also, it does not depend on state management tool

2024-03-15 13:22 UTC, ipakhomov commented on src/interceptors/on-request-refresh-token.ts
> +    // TODO: Fix sessionExpiry is retrieved before its set in authListenerMiddleware
We need to avoid such comments in the library

2024-03-15 13:22 UTC, ipakhomov commented on src/interceptors/on-request-refresh-token.ts
> +      (!sessionExpiry?.isValid || sessionExpiry < DateTime.local()) &&
Let's try to get rid of `luxon` dependency in this library.
We can use [this library](https://www.npmjs.com/package/jwt-decode) to decode token and find out if token is expired:

```ts
import { jwtDecode } from "jwt-decode";
...
const { exp } = jwtDecode(token);
const isTokenExpired = (new Date().getTime() / 1000) > exp; 
```

This can be moved to some [utility like this](https://github.com/RonasIT/react-native-starter/blob/main/libs/shared/data-access/api/auth/utils/check-is-token-expired.ts).

Please note that we'll need a polyfill for react native as [described here](https://github.com/auth0/jwt-decode?tab=readme-ov-file#polyfilling-atob). Please use the `base-64` for it

2024-03-15 13:22 UTC, ipakhomov commented on src/interceptors/on-response-refresh-token.ts
> +import { StatusCodes } from 'http-status-codes';
This data can be taken from axios as well

```suggestion
import { HttpStatusCode } from 'axios';
```

2024-03-15 13:22 UTC, ipakhomov commented on src/interfaces/refresh-token-options.ts
> +export interface SessionExpiryRefreshInterceptorArgs {
Let's declare thin interface near the `onResponseSessionExpiryRefreshInterceptor`.

2024-03-15 13:22 UTC, ipakhomov commented on src/service.ts
> +export const apiService = new ApiService();
As discussed - this library should not initiate any instances of services

2024-03-15 13:22 UTC, ipakhomov commented on src/interfaces/auth-configuration.ts
> +export interface AuthConfiguration {
Let's make this a type and move into `types` directory

2024-03-15 13:22 UTC, ipakhomov commented on src/interfaces/token-interceptor-options.ts
> +export interface TokenInterceptorOptions {
Same here - let's declare this type in the `src/interceptors/token-interceptor.ts` file.

Please apply the same for other interceptors if any, and get rid the `src/interfaces` dir

2024-03-15 14:38 UTC, ipakhomov commented
@RuslanAktaev also, could you please add [this interceptor](https://github.com/RonasIT/react-native-starter/blob/main/libs/shared/data-access/api-client/interceptors/unauthorized.ts)? It may be useful for some projects

2024-04-29 08:27 UTC, RuslanAktaev commented
@ipakhomov review please

2024-05-01 06:57 UTC, ipakhomov requested changes
@RuslanAktaev thanks for the update! A few more minor suggestions

2024-05-01 06:57 UTC, ipakhomov commented on .prettierrc.js
> +  trailingComma: 'none'
Could you please remove this line, and re-format the code? We use trailing commas by default

2024-05-01 06:57 UTC, ipakhomov commented on README.md
> +    dispatch(authActions.saveToken({ token, ttl }));
Let's avoid redux mentions in code examples:

```suggestion
    /* do something with token and ttl */
```

2024-05-01 06:57 UTC, ipakhomov commented on src/interceptors/on-request-refresh-token.ts
> +export const onRequestSessionExpiryRefreshInterceptor =
Could you please rename this interceptor and types to match file name?

`onRequestRefreshToken`

2024-05-01 06:57 UTC, ipakhomov commented on src/service.ts
> +export type UpdatedAxiosDefaults = Partial<
What's the purpose of this type?

2024-05-01 06:57 UTC, ipakhomov commented on src/interceptors/on-request-refresh-token.ts
> +global.atob = decode;
I suppose this line should be moved into file with `checkIsTokenExpired` definition

2024-05-01 06:57 UTC, ipakhomov commented on src/interceptors/on-response-refresh-token.ts
> +export const onResponseSessionExpiryRefreshInterceptor =
Could you please rename this interceptor and types to match file name?

2024-05-03 17:57 UTC, RuslanAktaev commented
@ipakhomov fixed! Review please

2024-05-04 07:31 UTC, ipakhomov requested changes
@RuslanAktaev sorry, few more comments

2024-05-04 07:31 UTC, ipakhomov commented on package.json
> +    "*.{js,css,md}": "prettier --write"
Please include typescript files into the pre-commit hook

2024-05-04 07:31 UTC, ipakhomov commented on src/interceptors/on-request-refresh-token.ts
> +export const onRequestRefreshToken =
After another look I think we should include the `Interceptor` suffix into the name for consistency with other interceptors:

```suggestion
export const onRequestRefreshTokenInterceptor =
```

2024-05-04 07:31 UTC, ipakhomov commented on src/interceptors/on-response-refresh-token.ts
> +export const onResponseRefreshToken =
```suggestion
export const onResponseRefreshTokenInterceptor =
```

2024-05-04 07:31 UTC, ipakhomov commented on package.json
> +    "format": "prettier --write .",
Let's update these scripts to match our other projects:

```suggestion
    "lint": "npx tsc && npx eslint ./",
    "format": "npx prettier --write . && npm run lint -- --fix",
```

2024-05-04 07:35 UTC, ipakhomov requested changes

2024-05-04 07:35 UTC, ipakhomov commented on src/interceptors/form-data.ts
> +import { forOwn, some, values } from 'lodash';
This is the one place this library uses lodash. Could you please refactor the code to avoid it and get-rid the dependency?

2024-05-05 17:51 UTC, RuslanAktaev commented
@ipakhomov done.

2024-05-06 14:47 UTC, ipakhomov approved these changes

2024-05-06 14:47 UTC, ipakhomov commented
@RuslanAktaev thanks! Merged!

2024-05-06 14:48 UTC, merged